name: Publish Website
on:
    workflow_dispatch:
    push:
      branches:
        - master

env:
  DOTNET_VERSION: '6.0.x'
  NODE_VERSION: '16.13.0'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout the repo
      - uses: actions/checkout@master
      
      # Setup dotnet
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '${{ env.DOTNET_VERSION }}'

      # Install Node and gulp-cli
      - name: Install Node and gulp-cli
        uses: actions/setup-node@v2
        with:
          node-version: '${{ env.NODE_VERSION }}'
      - run: corepack enable
      - run: npm install --global gulp-cli
      
      # Build Statiq
      - name: Build Statiq
        run: dotnet run
      
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: output
          GITHUB_TOKEN: ${{ secrets.STATIQ_TOKEN }}
          CLEAR_GLOBS_FILE: ".clear-target-files"