name: Build Pull Request
on:
  pull_request:

env:
  DOTNET_VERSION: '6.0.x'
  NODE_VERSION: '16.13.0'

jobs:
  build-pull-request:
    runs-on: ubuntu-latest
    steps:

      # Checkout the repo
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      # Setup .dotnet
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '${{ env.DOTNET_VERSION }}'

      # Install Node and gulp-cli
      - name: Install Node and gulp-cli
        uses: actions/setup-node@v2
        with:
          node-version: '${{ env.NODE_VERSION }}'
      - run: corepack enable
      - run: npm install --global gulp-cli
      
      # Build Statiq
      - name: Build Statiq
        run: dotnet run